-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="DNT {0} second duration between Corpse consumptions"
			}
		},
		stats={
			[1]="base_secondary_skill_effect_duration"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="DNT Maximum {0} Corpse Beetle"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="DNT Maximum {0} Corpse Beetles"
			}
		},
		stats={
			[1]="maximum_corpse_beetles_allowed"
		}
	},
	["base_secondary_skill_effect_duration"]=1,
	["maximum_corpse_beetles_allowed"]=2,
	parent="skill_stat_descriptions"
}