-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Soul Core of Tacati"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 15% chance to Poison on Hit with this weapon\nArmour: +7% to Chaos Resistance",
	req = { level = 35, },
}
itemBases["Soul Core of Opiloti"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 15% chance to cause Bleeding on Hit\nArmour: 10% increased Charm Charges gained",
	req = { level = 35, },
}
itemBases["Soul Core of Jiquani"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Recover 2% of maximum Life on Kill\nArmour: 2% increased maximum Life",
	req = { level = 35, },
}
itemBases["Soul Core of Zalatl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Recover 2% of maximum Mana on Kill\nArmour: 2% increased maximum Mana",
	req = { level = 35, },
}
itemBases["Soul Core of Citaqualotl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 30% increased Elemental Damage with Attacks\nArmour: +5% to all Elemental Resistances",
	req = { level = 35, },
}
itemBases["Soul Core of Puhuarte"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 30% increased chance to Ignite\nArmour: +1% to Maximum Fire Resistance",
	req = { level = 35, },
}
itemBases["Soul Core of Tzamoto"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 20% increased Freeze Buildup\nArmour: +1% to Maximum Cold Resistance",
	req = { level = 35, },
}
itemBases["Soul Core of Xopec"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 30% increased chance to Shock\nArmour: +1% to Maximum Lightning Resistance",
	req = { level = 35, },
}
itemBases["Soul Core of Azcapa"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +15 to Spirit\nArmour: 5% increased Quantity of Gold Dropped by Slain Enemies",
	req = { level = 35, },
}
itemBases["Soul Core of Topotante"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Attacks with this Weapon Penetrate 15% Elemental Resistances\nArmour: 15% increased Elemental Ailment Threshold",
	req = { level = 35, },
}
itemBases["Soul Core of Quipolatl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 5% increased Attack Speed\nArmour: 10% reduced Slowing Potency of Debuffs on You",
	req = { level = 35, },
}
itemBases["Soul Core of Ticaba"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +12% to Critical Damage Bonus\nArmour: Hits against you have 10% reduced Critical Damage Bonus",
	req = { level = 35, },
}
itemBases["Soul Core of Atmohua"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Convert 20% of Requirements to Strength\nArmour: Convert 20% of Requirements to Strength",
	req = { level = 35, },
}
itemBases["Soul Core of Cholotl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Convert 20% of Requirements to Dexterity\nArmour: Convert 20% of Requirements to Dexterity",
	req = { level = 35, },
}
itemBases["Soul Core of Zantipi"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Convert 20% of Requirements to Intelligence\nArmour: Convert 20% of Requirements to Intelligence",
	req = { level = 35, },
}

itemBases["Desert Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 7 to 11 Fire Damage\nArmour: +12% to Fire Resistance",
	req = { level = 31, },
}
itemBases["Glacial Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 6 to 10 Cold Damage\nArmour: +12% to Cold Resistance",
	req = { level = 31, },
}
itemBases["Storm Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 1 to 20 Lightning Damage\nArmour: +12% to Lightning Resistance",
	req = { level = 31, },
}
itemBases["Iron Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 20% increased Physical Damage\nArmour: 20% increased Armour, Evasion and Energy Shield",
	req = { level = 31, },
}
itemBases["Body Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 2.5% of Physical Damage as Life\nArmour: +30 to maximum Life",
	req = { level = 37, },
}
itemBases["Mind Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 2% of Physical Damage as Mana\nArmour: +25 to maximum Mana",
	req = { level = 37, },
}
itemBases["Rebirth Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 20 Life per Enemy Killed\nArmour: Regenerate 0.3% of maximum Life per second",
	req = { level = 45, },
}
itemBases["Inspiration Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 16 Mana per Enemy Killed\nArmour: 15% increased Mana Regeneration Rate",
	req = { level = 45, },
}
itemBases["Stone Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Causes 25% increased Stun Buildup\nArmour: +40 to Stun Threshold",
	req = { level = 41, },
}
itemBases["Vision Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +80 to Accuracy Rating\nArmour: 10% increased Life and Mana Recovery from Flasks",
	req = { level = 41, },
}
itemBases["Lesser Desert Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 4 to 6 Fire Damage\nArmour: +10% to Fire Resistance",
	req = { level = 5, },
}
itemBases["Lesser Glacial Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 3 to 5 Cold Damage\nArmour: +10% to Cold Resistance",
	req = { level = 5, },
}
itemBases["Lesser Storm Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 1 to 10 Lightning Damage\nArmour: +10% to Lightning Resistance",
	req = { level = 5, },
}
itemBases["Lesser Iron Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 15% increased Physical Damage\nArmour: 15% increased Armour, Evasion and Energy Shield",
	req = { level = 5, },
}
itemBases["Lesser Body Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 2% of Physical Damage as Life\nArmour: +20 to maximum Life",
	req = { level = 11, },
}
itemBases["Lesser Mind Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 1.5% of Physical Damage as Mana\nArmour: +15 to maximum Mana",
	req = { level = 11, },
}
itemBases["Lesser Rebirth Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 10 Life per Enemy Killed\nArmour: Regenerate 0.25% of maximum Life per second",
	req = { level = 21, },
}
itemBases["Lesser Inspiration Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 8 Mana per Enemy Killed\nArmour: 12% increased Mana Regeneration Rate",
	req = { level = 21, },
}
itemBases["Lesser Stone Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Causes 20% increased Stun Buildup\nArmour: +30 to Stun Threshold",
	req = { level = 16, },
}
itemBases["Lesser Vision Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +50 to Accuracy Rating\nArmour: 8% increased Life and Mana Recovery from Flasks",
	req = { level = 16, },
}
itemBases["Greater Desert Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 13 to 16 Fire Damage\nArmour: +14% to Fire Resistance",
	req = { level = 52, },
}
itemBases["Greater Glacial Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 9 to 15 Cold Damage\nArmour: +14% to Cold Resistance",
	req = { level = 52, },
}
itemBases["Greater Storm Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 1 to 30 Lightning Damage\nArmour: +14% to Lightning Resistance",
	req = { level = 52, },
}
itemBases["Greater Iron Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 25% increased Physical Damage\nArmour: 25% increased Armour, Evasion and Energy Shield",
	req = { level = 52, },
}
itemBases["Greater Body Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 3% of Physical Damage as Life\nArmour: +40 to maximum Life",
	req = { level = 57, },
}
itemBases["Greater Mind Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 2.5% of Physical Damage as Mana\nArmour: +35 to maximum Mana",
	req = { level = 57, },
}
itemBases["Greater Rebirth Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 30 Life per Enemy Killed\nArmour: Regenerate 0.35% of maximum Life per second",
	req = { level = 62, },
}
itemBases["Greater Inspiration Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 24 Mana per Enemy Killed\nArmour: 18% increased Mana Regeneration Rate",
	req = { level = 62, },
}
itemBases["Greater Stone Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Causes 30% increased Stun Buildup\nArmour: +50 to Stun Threshold",
	req = { level = 59, },
}
itemBases["Greater Vision Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +110 to Accuracy Rating\nArmour: 12% increased Life and Mana Recovery from Flasks",
	req = { level = 59, },
}
itemBases["Lesser Robust Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +6 to Strength\nArmour: +6 to Strength",
	req = { level = 5, },
}
itemBases["Robust Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +8 to Strength\nArmour: +8 to Strength",
	req = { level = 31, },
}
itemBases["Greater Robust Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +10 to Strength\nArmour: +10 to Strength",
	req = { level = 52, },
}
itemBases["Lesser Adept Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +5 to Dexterity\nArmour: +6 to Dexterity",
	req = { level = 5, },
}
itemBases["Adept Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +8 to Dexterity\nArmour: +8 to Dexterity",
	req = { level = 31, },
}
itemBases["Greater Adept Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +10 to Dexterity\nArmour: +10 to Dexterity",
	req = { level = 52, },
}
itemBases["Lesser Resolve Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +6 to Intelligence\nArmour: +6 to Intelligence",
	req = { level = 5, },
}
itemBases["Resolve Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +8 to Intelligence\nArmour: +8 to Intelligence",
	req = { level = 31, },
}
itemBases["Greater Resolve Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +10 to Intelligence\nArmour: +10 to Intelligence",
	req = { level = 52, },
}
itemBases["Lesser Tempered Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_lesser = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 3 to 4 Physical Damage\nArmour: 6 to 9 Physical Thorns damage",
	req = { level = 5, },
}
itemBases["Tempered Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_normal = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 6 to 9 Physical Damage\nArmour: 14 to 21 Physical Thorns damage",
	req = { level = 31, },
}
itemBases["Greater Tempered Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { rune_greater = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 9 to 12 Physical Damage\nArmour: 31 to 52 Physical Thorns damage",
	req = { level = 52, },
}
itemBases["Greater Rune of Leadership"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Minions gain 10% of their Physical Damage as Extra Lightning Damage\nArmour: Minions take 10% of Physical Damage as Lightning Damage",
	req = { level = 65, },
}
itemBases["Greater Rune of Tithing"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Meta Skills gain 10% increased Energy\nArmour: 1 to 10 Lightning Thorns damage",
	req = { level = 65, },
}
itemBases["Greater Rune of Alacrity"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 8% increased Skill Speed\nArmour: Debuffs on you expire 8% faster",
	req = { level = 65, },
}
itemBases["Greater Rune of Nobility"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Attacks with this Weapon have 10% chance to inflict Lightning Exposure\nArmour: 10% reduced effect of Shock on you",
	req = { level = 65, },
}
