-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Minion active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["MeleeAtAnimationSpeed"] = {
	name = "Basic Attack",
	hidden = true,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Basic Attack",
			baseEffectiveness = 0,
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
			},
			stats = {
				"skill_can_fire_arrows",
				"skill_can_fire_wand_projectiles",
				"action_attack_or_cast_time_uses_animation_length",
				"projectile_uses_contact_position",
				"use_scaled_contact_offset",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["MinionMelee"] = {
	name = "Basic Attack",
	hidden = true,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Basic Attack",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
			},
			stats = {
				"skill_can_fire_arrows",
				"skill_can_fire_wand_projectiles",
				"projectile_uses_contact_position",
				"use_scaled_contact_offset",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["MinionMeleeStep"] = {
	name = "Basic Attack",
	hidden = true,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Basic Attack",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
			},
			constantStats = {
				{ "melee_conditional_step_distance", 10 },
			},
			stats = {
				"skill_can_fire_arrows",
				"skill_can_fire_wand_projectiles",
				"projectile_uses_contact_position",
				"use_scaled_contact_offset",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["MinionMeleeBow"] = {
	name = "Basic Attack",
	hidden = true,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Basic Attack",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				projectile = true,
			},
			constantStats = {
				{ "arrow_projectile_variation", 1002 },
			},
			stats = {
				"skill_can_fire_arrows",
				"skill_can_fire_wand_projectiles",
				"projectile_uses_contact_position",
				"use_scaled_contact_offset",
				"maintain_projectile_direction_when_using_contact_position",
				"check_for_targets_between_initiator_and_projectile_source",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["GasShotSkeletonSniperMinion"] = {
	name = "Gas Arrow",
	hidden = true,
	description = "Rain an arrow down from above, creating a cloud of flammable poisonous gas where it lands. The cloud will detonate if hit by a Detonator skill or if an Ignited enemy touches it, creating a fiery explosion.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.Area] = true, [SkillType.ProjectileNumber] = true, [SkillType.ProjectileSpeed] = true, [SkillType.Rain] = true, [SkillType.DamageOverTime] = true, [SkillType.Cooldown] = true, [SkillType.Duration] = true, [SkillType.GroundTargetedProjectile] = true, [SkillType.CreatesGroundEffect] = true, [SkillType.NoAttackInPlace] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { attackSpeedMultiplier = 20, storedUses = 1, baseMultiplier = 0.8, cooldown = 6, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Impact",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "sniper_gas_shot_statset_0",
			baseFlags = {
				attack = true,
				projectile = true,
				area = true,
			},
			constantStats = {
				{ "active_skill_base_area_of_effect_radius", 14 },
				{ "active_skill_base_secondary_area_of_effect_radius", 20 },
				{ "command_minion_marker_additional_time_ms", 300 },
			},
			stats = {
				"is_commandable_skill",
				"base_is_projectile",
				"is_area_damage",
				"visual_hit_effect_chaos_is_green",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
				"quality_display_active_skill_ground_effect_area_of_effect_+%_final_per_second_max_is_gem",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
		[2] = {
			label = "Poison Cloud",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "sniper_gas_shot_statset_1",
			baseFlags = {
				attack = true,
				area = true,
				duration = true,
			},
			constantStats = {
				{ "active_skill_base_area_of_effect_radius", 14 },
				{ "active_skill_base_secondary_area_of_effect_radius", 20 },
				{ "command_minion_marker_additional_time_ms", 300 },
				{ "base_skill_effect_duration", 8000 },
				{ "active_skill_ground_effect_area_of_effect_+%_final_per_second", 20 },
				{ "active_skill_ground_effect_area_of_effect_+%_final_per_second_max", 80 },
			},
			stats = {
				"is_commandable_skill",
				"base_is_projectile",
				"is_area_damage",
				"visual_hit_effect_chaos_is_green",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
				"quality_display_active_skill_ground_effect_area_of_effect_+%_final_per_second_max_is_gem",
				"display_statset_no_hit_damage",
				"display_statset_hide_usage_stats",
				"display_fake_attack_hit_poison",
				"display_skill_poisons_without_hit",
			},
			levels = {
				[1] = { baseMultiplier = 2.2, actorLevel = 1, },
			},
		},
		[3] = {
			label = "Explosion",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "sniper_gas_shot_statset_2",
			baseFlags = {
				hit = true,
				area = true,
			},
			constantStats = {
				{ "active_skill_base_area_of_effect_radius", 14 },
				{ "active_skill_base_secondary_area_of_effect_radius", 20 },
				{ "command_minion_marker_additional_time_ms", 300 },
				{ "active_skill_base_physical_damage_%_to_convert_to_fire", 100 },
			},
			stats = {
				"is_commandable_skill",
				"base_is_projectile",
				"is_area_damage",
				"visual_hit_effect_chaos_is_green",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
				"quality_display_active_skill_ground_effect_area_of_effect_+%_final_per_second_max_is_gem",
			},
			levels = {
				[1] = { baseMultiplier = 6.3, actorLevel = 1, },
			},
		},
	}
}
skills["BoneshatterBruteMinion"] = {
	name = "Bonebreaker",
	hidden = true,
	description = "A Strike that causes a Heavy Stun on enemies that are Primed for Stun. Upon causing a Heavy Stun it will also create a Shockwave, dealing a large amount of damage in an area.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Melee] = true, [SkillType.Area] = true, [SkillType.Cooldown] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { attackSpeedMultiplier = 20, storedUses = 1, baseMultiplier = 1.8, cooldown = 4, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Initial Strike",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
			},
			constantStats = {
				{ "melee_range_+", 2 },
				{ "melee_conditional_step_distance", 3 },
			},
			stats = {
				"crushing_blow",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
		[2] = {
			label = "Shockwave",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				area = true,
			},
			constantStats = {
				{ "melee_range_+", 2 },
				{ "melee_conditional_step_distance", 3 },
				{ "active_skill_base_area_of_effect_radius", 20 },
			},
			stats = {
				"crushing_blow",
				"is_area_damage",
			},
			levels = {
				[1] = { baseMultiplier = 4.8, actorLevel = 1, },
			},
		},
	}
}
skills["ArcSkeletonMageMinion"] = {
	name = "Arc",
	hidden = true,
	description = "An arc of Lightning stretches from the caster to a targeted enemy and Chains on to other nearby enemies. Shocked enemies Hit release damaging pulses.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Chains] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.Lightning] = true, [SkillType.Unleashable] = true, [SkillType.Invokable] = true, [SkillType.UsableWhileMoving] = true, [SkillType.Area] = true, [SkillType.AreaSpell] = true, [SkillType.NoAttackInPlace] = true, },
	castTime = 1.25,
	qualityStats = {
	},
	levels = {
		[1] = { critChance = 9, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Arc",
			baseEffectiveness = 1.2000000476837,
			incrementalEffectiveness = 0.25,
			damageIncrementalEffectiveness = 0.037999998778105,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				spell = true,
				chaining = true,
			},
			constantStats = {
				{ "arc_chain_distance", 35 },
				{ "active_skill_shock_chance_+%_final", 100 },
			},
			stats = {
				"spell_minimum_base_lightning_damage",
				"spell_maximum_base_lightning_damage",
				"number_of_chains",
				"disable_visual_hit_effect",
			},
			notMinionStat = {
				"spell_minimum_base_lightning_damage",
				"spell_maximum_base_lightning_damage",
			},
			levels = {
				[1] = { 0.10000000149012, 1.8999999761581, 2, statInterpolation = { 3, 3, 1, }, actorLevel = 1, },
				[2] = { 0.10000000149012, 1.8999999761581, 2, statInterpolation = { 3, 3, 1, }, actorLevel = 20, },
				[3] = { 0.10000000149012, 1.8999999761581, 2, statInterpolation = { 3, 3, 1, }, actorLevel = 40, },
				[4] = { 0.10000000149012, 1.8999999761581, 2, statInterpolation = { 3, 3, 1, }, actorLevel = 60, },
			},
		},
	}
}
skills["DeathStormSkeletonStormMageMinion"] = {
	name = "Death Storm",
	hidden = true,
	description = "Lightning bolts strike all fallen Skeletons in the area, creating Shocked Ground around them.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Lightning] = true, [SkillType.Area] = true, [SkillType.Cooldown] = true, [SkillType.CreatesGroundEffect] = true, [SkillType.NoAttackInPlace] = true, },
	castTime = 2,
	qualityStats = {
	},
	levels = {
		[1] = { critChance = 10, storedUses = 1, levelRequirement = 0, cooldown = 5, },
	},
	statSets = {
		[1] = {
			label = "Death Storm",
			baseEffectiveness = 9,
			incrementalEffectiveness = 0.25,
			damageIncrementalEffectiveness = 0.041499998420477,
			statDescriptionScope = "death_storm",
			baseFlags = {
				spell = true,
				area = true,
				hit = true,
			},
			constantStats = {
				{ "ground_lightning_art_variation", 1003 },
				{ "active_skill_base_area_of_effect_radius", 20 },
				{ "active_skill_base_secondary_area_of_effect_radius", 20 },
				{ "base_skill_effect_duration", 6000 },
			},
			stats = {
				"spell_minimum_base_lightning_damage",
				"spell_maximum_base_lightning_damage",
				"is_commandable_skill",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
			},
			notMinionStat = {
				"spell_minimum_base_lightning_damage",
				"spell_maximum_base_lightning_damage",
			},
			levels = {
				[1] = { 0.30000001192093, 1.7000000476837, statInterpolation = { 3, 3, }, actorLevel = 1, },
			},
		},
	}
}
skills["FrostBoltSkeletonMageMinion"] = {
	name = "Ice Shard",
	hidden = true,
	skillTypes = { [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, [SkillType.Cold] = true, [SkillType.Unleashable] = true, [SkillType.Area] = true, },
	castTime = 1.25,
	qualityStats = {
	},
	levels = {
		[1] = { critChance = 11, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Projectile",
			baseEffectiveness = 1.0499999523163,
			incrementalEffectiveness = 0.25,
			damageIncrementalEffectiveness = 0.034499999135733,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				spell = true,
				projectile = true,
			},
			constantStats = {
				{ "monster_projectile_variation", 1064 },
				{ "base_chance_to_freeze_%", 100 },
				{ "active_skill_hit_damage_freeze_multiplier_+%_final", 100 },
				{ "projectile_maximum_duration_override_ms", 180 },
			},
			stats = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
				"base_is_projectile",
				"projectile_uses_contact_position",
				"check_for_targets_between_initiator_and_projectile_source",
				"maintain_projectile_direction_when_using_contact_position",
			},
			notMinionStat = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
			},
			levels = {
				[1] = { 0.80000001192093, 1.2000000476837, statInterpolation = { 3, 3, }, actorLevel = 1, },
			},
		},
		[2] = {
			label = "Explosion",
			baseEffectiveness = 0.85000002384186,
			incrementalEffectiveness = 0.25,
			damageIncrementalEffectiveness = 0.034499999135733,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				area = true,
				hit = true,
			},
			constantStats = {
				{ "monster_projectile_variation", 1064 },
				{ "base_chance_to_freeze_%", 100 },
				{ "active_skill_hit_damage_freeze_multiplier_+%_final", 100 },
				{ "projectile_maximum_duration_override_ms", 180 },
				{ "active_skill_base_area_of_effect_radius", 8 },
			},
			stats = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
				"base_is_projectile",
				"projectile_uses_contact_position",
				"check_for_targets_between_initiator_and_projectile_source",
				"maintain_projectile_direction_when_using_contact_position",
				"is_area_damage",
				"display_statset_hide_usage_stats",
			},
			notMinionStat = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
			},
			levels = {
				[1] = { 0.80000001192093, 1.2000000476837, critChance = 23, statInterpolation = { 3, 3, }, actorLevel = 1, },
			},
		},
	}
}
skills["IceBombSkeletonMageMinion"] = {
	name = "Ice Bomb",
	hidden = true,
	description = "Crystallises the air into icy shards that explode outwards when they hit the ground.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Duration] = true, [SkillType.Cold] = true, [SkillType.Minion] = true, [SkillType.Damage] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.Area] = true, [SkillType.AreaSpell] = true, [SkillType.Cascadable] = true, },
	castTime = 1.25,
	qualityStats = {
	},
	levels = {
		[1] = { critChance = 12, storedUses = 1, levelRequirement = 0, cooldown = 8, },
	},
	statSets = {
		[1] = {
			label = "Ice Bomb",
			baseEffectiveness = 5,
			incrementalEffectiveness = 0.25,
			damageIncrementalEffectiveness = 0.041499998420477,
			statDescriptionScope = "ice_bomb",
			baseFlags = {
				spell = true,
				duration = true,
			},
			constantStats = {
				{ "active_skill_base_area_of_effect_radius", 26 },
				{ "active_skill_chill_effect_+%_final", 100 },
			},
			stats = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
				"is_commandable_skill",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
			},
			notMinionStat = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
			},
			levels = {
				[1] = { 0.80000001192093, 1.2000000476837, statInterpolation = { 3, 3, }, actorLevel = 1, },
			},
		},
	}
}
skills["HealSkeletonClericMinion"] = {
	name = "Heal Buff",
	hidden = true,
	skillTypes = { [SkillType.Buff] = true, [SkillType.Duration] = true, [SkillType.Spell] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Heal",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "add_buff_to_target",
			baseFlags = {
			},
			constantStats = {
				{ "base_skill_effect_duration", 4000 },
			},
			stats = {
				"skeletal_cleric_grants_base_life_regeneration_rate_per_minute",
				"display_minion_heal",
			},
			levels = {
				[1] = { 776, statInterpolation = { 1, }, actorLevel = 1, },
				[2] = { 1410, statInterpolation = { 1, }, actorLevel = 3, },
				[3] = { 2109, statInterpolation = { 1, }, actorLevel = 5, },
				[4] = { 2884, statInterpolation = { 1, }, actorLevel = 7, },
				[5] = { 3695, statInterpolation = { 1, }, actorLevel = 9, },
				[6] = { 4599, statInterpolation = { 1, }, actorLevel = 11, },
				[7] = { 5547, statInterpolation = { 1, }, actorLevel = 13, },
				[8] = { 6591, statInterpolation = { 1, }, actorLevel = 15, },
				[9] = { 7717, statInterpolation = { 1, }, actorLevel = 17, },
				[10] = { 8925, statInterpolation = { 1, }, actorLevel = 19, },
				[11] = { 10184, statInterpolation = { 1, }, actorLevel = 21, },
				[12] = { 11587, statInterpolation = { 1, }, actorLevel = 23, },
				[13] = { 13099, statInterpolation = { 1, }, actorLevel = 25, },
				[14] = { 14673, statInterpolation = { 1, }, actorLevel = 27, },
				[15] = { 16435, statInterpolation = { 1, }, actorLevel = 29, },
				[16] = { 18306, statInterpolation = { 1, }, actorLevel = 31, },
				[17] = { 20314, statInterpolation = { 1, }, actorLevel = 33, },
				[18] = { 22439, statInterpolation = { 1, }, actorLevel = 35, },
				[19] = { 24779, statInterpolation = { 1, }, actorLevel = 37, },
				[20] = { 27243, statInterpolation = { 1, }, actorLevel = 39, },
				[21] = { 29927, statInterpolation = { 1, }, actorLevel = 41, },
				[22] = { 32745, statInterpolation = { 1, }, actorLevel = 43, },
				[23] = { 35801, statInterpolation = { 1, }, actorLevel = 45, },
				[24] = { 39046, statInterpolation = { 1, }, actorLevel = 47, },
				[25] = { 42572, statInterpolation = { 1, }, actorLevel = 49, },
				[26] = { 46315, statInterpolation = { 1, }, actorLevel = 51, },
				[27] = { 50317, statInterpolation = { 1, }, actorLevel = 53, },
				[28] = { 54638, statInterpolation = { 1, }, actorLevel = 55, },
				[29] = { 59219, statInterpolation = { 1, }, actorLevel = 57, },
				[30] = { 64126, statInterpolation = { 1, }, actorLevel = 59, },
				[31] = { 69402, statInterpolation = { 1, }, actorLevel = 61, },
				[32] = { 75060, statInterpolation = { 1, }, actorLevel = 63, },
				[33] = { 81057, statInterpolation = { 1, }, actorLevel = 65, },
				[34] = { 87502, statInterpolation = { 1, }, actorLevel = 67, },
				[35] = { 94367, statInterpolation = { 1, }, actorLevel = 69, },
				[36] = { 101706, statInterpolation = { 1, }, actorLevel = 71, },
				[37] = { 109584, statInterpolation = { 1, }, actorLevel = 73, },
				[38] = { 118001, statInterpolation = { 1, }, actorLevel = 75, },
				[39] = { 126925, statInterpolation = { 1, }, actorLevel = 77, },
				[40] = { 136534, statInterpolation = { 1, }, actorLevel = 79, },
			},
		},
	}
}
skills["FireBombSkeletonMinion"] = {
	name = "Fire Bomb",
	hidden = true,
	description = "Attacks with a bouncing bomb that explodes on hit.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.Area] = true, [SkillType.ProjectileNumber] = true, [SkillType.ProjectileSpeed] = true, [SkillType.Duration] = true, [SkillType.Grenade] = true, [SkillType.CreatesGroundEffect] = true, [SkillType.DetonatesAfterTime] = true, [SkillType.Projectile] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Fire Bomb",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				area = true,
				duration = true,
			},
			constantStats = {
				{ "base_skill_detonation_time", 2000 },
				{ "active_skill_base_physical_damage_%_to_convert_to_fire", 70 },
				{ "active_skill_base_area_of_effect_radius", 16 },
			},
			stats = {
				"base_is_projectile",
				"projectile_ballistic_angle_from_reference_event",
				"is_area_damage",
				"grenades_target_at_half_monster_height",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
		[2] = {
			label = "Hidden",
			baseEffectiveness = 8,
			incrementalEffectiveness = 0.034650001674891,
			damageIncrementalEffectiveness = 0.012719999998808,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
			},
			constantStats = {
				{ "base_skill_detonation_time", 2000 },
				{ "active_skill_base_physical_damage_%_to_convert_to_fire", 70 },
				{ "active_skill_base_area_of_effect_radius", 16 },
				{ "base_secondary_skill_effect_duration", 0 },
			},
			stats = {
				"base_fire_damage_to_deal_per_minute",
				"base_is_projectile",
				"projectile_ballistic_angle_from_reference_event",
				"is_area_damage",
				"grenades_target_at_half_monster_height",
			},
			notMinionStat = {
				"base_fire_damage_to_deal_per_minute",
			},
			levels = {
				[1] = { 16.666667039196, statInterpolation = { 3, }, actorLevel = 1, },
			},
		},
	}
}
skills["DestructiveLinkSkeletonBombadierMinion"] = {
	name = "Explosive Demise",
	baseTypeName = "Explosive Demise",
	color = 2,
	description = "Detonate an allied Minion whose current Life is below a threshold, dealing heavy Attack damage to nearby enemies.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Cooldown] = true, [SkillType.Area] = true, [SkillType.Fire] = true, [SkillType.Damage] = true, [SkillType.NoAttackInPlace] = true, },
	castTime = 1,
	qualityStats = {
		{ "arsonist_destructive_link_%_of_life_as_fire_damage", 0.2 },
	},
	levels = {
		[1] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[2] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[3] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[4] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[5] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[6] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[7] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[8] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[9] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[10] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[11] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[12] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[13] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[14] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[15] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[16] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[17] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[18] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[19] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[20] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[21] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[22] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[23] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[24] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[25] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[26] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[27] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[28] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[29] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[30] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[31] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[32] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[33] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[34] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[35] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[36] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[37] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[38] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[39] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
		[40] = { baseMultiplier = 3, storedUses = 1, levelRequirement = 0, cooldown = 3, },
	},
	statSets = {
		[1] = {
			label = "Explosive Demise",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "bombadier_destructive_link",
			baseFlags = {
				area = true,
				spell = true,
			},
			constantStats = {
				{ "active_skill_base_area_of_effect_radius", 24 },
				{ "arsonist_destructive_link_%_of_life_as_fire_damage", 8 },
				{ "active_skill_base_physical_damage_%_to_convert_to_fire", 100 },
			},
			stats = {
				"command_minion_target_ally_below_x_life",
				"is_commandable_skill",
				"is_area_damage",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
				"quality_display_arsonist_is_gem",
			},
			levels = {
				[1] = { 30, statInterpolation = { 1, }, actorLevel = 1, },
				[2] = { 52, statInterpolation = { 1, }, actorLevel = 3, },
				[3] = { 77, statInterpolation = { 1, }, actorLevel = 5, },
				[4] = { 105, statInterpolation = { 1, }, actorLevel = 7, },
				[5] = { 134, statInterpolation = { 1, }, actorLevel = 9, },
				[6] = { 168, statInterpolation = { 1, }, actorLevel = 11, },
				[7] = { 203, statInterpolation = { 1, }, actorLevel = 13, },
				[8] = { 243, statInterpolation = { 1, }, actorLevel = 15, },
				[9] = { 286, statInterpolation = { 1, }, actorLevel = 17, },
				[10] = { 333, statInterpolation = { 1, }, actorLevel = 19, },
				[11] = { 383, statInterpolation = { 1, }, actorLevel = 21, },
				[12] = { 439, statInterpolation = { 1, }, actorLevel = 23, },
				[13] = { 500, statInterpolation = { 1, }, actorLevel = 25, },
				[14] = { 564, statInterpolation = { 1, }, actorLevel = 27, },
				[15] = { 636, statInterpolation = { 1, }, actorLevel = 29, },
				[16] = { 714, statInterpolation = { 1, }, actorLevel = 31, },
				[17] = { 799, statInterpolation = { 1, }, actorLevel = 33, },
				[18] = { 889, statInterpolation = { 1, }, actorLevel = 35, },
				[19] = { 989, statInterpolation = { 1, }, actorLevel = 37, },
				[20] = { 1096, statInterpolation = { 1, }, actorLevel = 39, },
				[21] = { 1213, statInterpolation = { 1, }, actorLevel = 41, },
				[22] = { 1338, statInterpolation = { 1, }, actorLevel = 43, },
				[23] = { 1474, statInterpolation = { 1, }, actorLevel = 45, },
				[24] = { 1620, statInterpolation = { 1, }, actorLevel = 47, },
				[25] = { 1780, statInterpolation = { 1, }, actorLevel = 49, },
				[26] = { 1951, statInterpolation = { 1, }, actorLevel = 51, },
				[27] = { 2137, statInterpolation = { 1, }, actorLevel = 53, },
				[28] = { 2338, statInterpolation = { 1, }, actorLevel = 55, },
				[29] = { 2554, statInterpolation = { 1, }, actorLevel = 57, },
				[30] = { 2788, statInterpolation = { 1, }, actorLevel = 59, },
				[31] = { 3040, statInterpolation = { 1, }, actorLevel = 61, },
				[32] = { 3313, statInterpolation = { 1, }, actorLevel = 63, },
				[33] = { 3606, statInterpolation = { 1, }, actorLevel = 65, },
				[34] = { 3923, statInterpolation = { 1, }, actorLevel = 67, },
				[35] = { 4263, statInterpolation = { 1, }, actorLevel = 69, },
				[36] = { 4631, statInterpolation = { 1, }, actorLevel = 71, },
				[37] = { 5028, statInterpolation = { 1, }, actorLevel = 73, },
				[38] = { 5456, statInterpolation = { 1, }, actorLevel = 75, },
				[39] = { 5915, statInterpolation = { 1, }, actorLevel = 77, },
				[40] = { 6412, statInterpolation = { 1, }, actorLevel = 79, },
			},
		},
	}
}
skills["EnrageSkeletonReaverMinion"] = {
	name = "Enrage",
	hidden = true,
	description = "Enrage all Skeletal Reavers, causing them to lose life over time and gain Rage on hit. Skeletal Reavers do more Attack Damage and gain increased Attack speed based on their Rage.",
	skillTypes = { [SkillType.Buff] = true, [SkillType.Cooldown] = true, [SkillType.NoAttackInPlace] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 0, cooldown = 4, },
	},
	statSets = {
		[1] = {
			label = "Enrage",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
			},
			constantStats = {
				{ "reaver_enrage_decay_rate_increase_+%_final", 20 },
				{ "reaver_enrage_base_life_%_degen_per_minute", 60 },
				{ "gain_x_rage_on_attack_hit", 2 },
			},
			stats = {
				"is_commandable_skill",
				"infinite_skill_effect_duration",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
				"base_deal_no_damage",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["GAAncestralJadeHulkLeapImpact"] = {
	name = "Leap Slam",
	hidden = true,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { baseMultiplier = 1.5, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Leap Slam",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				area = true,
			},
			stats = {
				"is_area_damage",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["TCAncestralLeagueKaruiHulk"] = {
	name = "Shield Charge",
	hidden = true,
	description = "Charges at an enemy, bashing it with the character's shield and striking it. This knocks it back and stuns it. Enemies in the way are pushed to the side. Damage and stun are proportional to distance travelled. Cannot be supported by Multistrike.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Sword"] = true,
		["One Handed Mace"] = true,
		["Flail"] = true,
		["Spear"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["Claw"] = true,
	},
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 0, cooldown = 7, },
	},
	statSets = {
		[1] = {
			label = "Shield Charge",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
				area = true,
			},
			stats = {
				"ignores_proximity_shield",
				"is_area_damage",
				"base_skill_can_be_blocked",
				"action_attack_or_cast_time_uses_animation_length",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["MPSAncestralTotemSpiritSoulCasterProjectile"] = {
	name = "Projectile Spell",
	hidden = true,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, [SkillType.Damage] = true, },
	castTime = 1.5,
	qualityStats = {
	},
	levels = {
		[1] = { critChance = 6, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Projectile Spell",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				spell = true,
				projectile = true,
			},
			constantStats = {
				{ "monster_projectile_variation", 1389 },
				{ "spell_maximum_action_distance_+%", -23 },
			},
			stats = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
				"base_is_projectile",
				"projectile_uses_contact_position",
				"use_scaled_contact_offset",
			},
			notMinionStat = {
				"spell_minimum_base_cold_damage",
				"spell_maximum_base_cold_damage",
			},
			levels = {
				[1] = { 0.80000001192093, 1.2000000476837, statInterpolation = { 3, 3, }, actorLevel = 1, },
			},
		},
	}
}
			skills["MinionInstability"] = {
				name = "Minion Instability",
				hidden = true,
				skillTypes = { [SkillType.Damage] = true, },
				qualityStats = {
				},
				levels = {
					[1] = { levelRequirement = 0, },
				},
				preDamageFunc = function(activeSkill, output)
					local skillData = activeSkill.skillData
					skillData.FireBonusMin = output.Life * skillData.selfFireExplosionLifeMultiplier
					skillData.FireBonusMax = output.Life * skillData.selfFireExplosionLifeMultiplier
				end,
				statSets = {
					[1] = {
						label = "Minion Instability",
						incrementalEffectiveness = 0,
						statDescriptionScope = "skill_stat_descriptions",
						baseFlags = {
						},
						baseMods = {
							skill("selfFireExplosionLifeMultiplier", 0.01, { type = "Multiplier", var = "MinionInstabilityBaseDamage" }),
							skill("showAverage", true),
						},
						constantStats = {
						},
						stats = {
						},
						levels = {
							[1] = { },
						},
					},
				}
			}

skills["GAAnimateWeaponMaceSlam"] = {
	name = "Mace Slam",
	hidden = true,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Area] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { attackSpeedMultiplier = -50, storedUses = 1, baseMultiplier = 1.8, cooldown = 10, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Slam (Mace)",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
				area = true,
			},
			stats = {
				"is_area_damage",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["DTTAnimateWeaponSpearDashStabImpact"] = {
	name = "Spear Dash",
	hidden = true,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Area] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { baseMultiplier = 1.8, levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Spear Dash",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
				area = true,
			},
			stats = {
				"is_area_damage",
				"action_attack_or_cast_time_uses_animation_length",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["GAAnimateWeaponQuarterstaffSweep"] = {
	name = "Quarterstaff Sweep",
	hidden = true,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Area] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { baseMultiplier = 0.9, storedUses = 1, levelRequirement = 0, cooldown = 10, },
	},
	statSets = {
		[1] = {
			label = "Sweep (Quarterstaff)",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
			},
			stats = {
				"is_area_damage",
				"action_attack_or_cast_time_uses_animation_length",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["RavenousSwarmAttack"] = {
	name = "Attack",
	hidden = true,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.Chaos] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
		[2] = { levelRequirement = 0, },
		[3] = { levelRequirement = 0, },
		[4] = { levelRequirement = 0, },
		[5] = { levelRequirement = 0, },
		[6] = { levelRequirement = 0, },
		[7] = { levelRequirement = 0, },
		[8] = { levelRequirement = 0, },
		[9] = { levelRequirement = 0, },
		[10] = { levelRequirement = 0, },
		[11] = { levelRequirement = 0, },
		[12] = { levelRequirement = 0, },
		[13] = { levelRequirement = 0, },
		[14] = { levelRequirement = 0, },
		[15] = { levelRequirement = 0, },
		[16] = { levelRequirement = 0, },
		[17] = { levelRequirement = 0, },
		[18] = { levelRequirement = 0, },
		[19] = { levelRequirement = 0, },
		[20] = { levelRequirement = 0, },
		[21] = { levelRequirement = 0, },
		[22] = { levelRequirement = 0, },
		[23] = { levelRequirement = 0, },
		[24] = { levelRequirement = 0, },
		[25] = { levelRequirement = 0, },
		[26] = { levelRequirement = 0, },
		[27] = { levelRequirement = 0, },
		[28] = { levelRequirement = 0, },
		[29] = { levelRequirement = 0, },
		[30] = { levelRequirement = 0, },
		[31] = { levelRequirement = 0, },
		[32] = { levelRequirement = 0, },
		[33] = { levelRequirement = 0, },
		[34] = { levelRequirement = 0, },
		[35] = { levelRequirement = 0, },
		[36] = { levelRequirement = 0, },
		[37] = { levelRequirement = 0, },
		[38] = { levelRequirement = 0, },
		[39] = { levelRequirement = 0, },
		[40] = { levelRequirement = 0, },
	},
	statSets = {
		[1] = {
			label = "Attack",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
				area = true,
			},
			stats = {
				"global_poison_on_hit",
			},
			levels = {
				[1] = { actorLevel = 1, },
				[2] = { actorLevel = 3.4519999027252, },
				[3] = { actorLevel = 6.7670001983643, },
				[4] = { actorLevel = 10.307999610901, },
				[5] = { actorLevel = 14.074999809265, },
				[6] = { actorLevel = 18.068000793457, },
				[7] = { actorLevel = 22.287000656128, },
				[8] = { actorLevel = 26.732000350952, },
				[9] = { actorLevel = 31.40299987793, },
				[10] = { actorLevel = 36.299999237061, },
				[11] = { actorLevel = 41.423000335693, },
				[12] = { actorLevel = 46.771999359131, },
				[13] = { actorLevel = 52.34700012207, },
				[14] = { actorLevel = 58.147998809814, },
				[15] = { actorLevel = 64.175003051758, },
				[16] = { actorLevel = 70.428001403809, },
				[17] = { actorLevel = 76.906997680664, },
				[18] = { actorLevel = 83.611999511719, },
				[19] = { actorLevel = 90.542999267578, },
				[20] = { actorLevel = 97.699996948242, },
				[21] = { actorLevel = 105.08300018311, },
				[22] = { actorLevel = 112.69200134277, },
				[23] = { actorLevel = 120.52700042725, },
				[24] = { actorLevel = 128.58799743652, },
				[25] = { actorLevel = 136.875, },
				[26] = { actorLevel = 145.38800048828, },
				[27] = { actorLevel = 154.12699890137, },
				[28] = { actorLevel = 163.09199523926, },
				[29] = { actorLevel = 172.28300476074, },
				[30] = { actorLevel = 181.69999694824, },
				[31] = { actorLevel = 191.34300231934, },
				[32] = { actorLevel = 201.21200561523, },
				[33] = { actorLevel = 211.30700683594, },
				[34] = { actorLevel = 221.62800598145, },
				[35] = { actorLevel = 232.17500305176, },
				[36] = { actorLevel = 242.94799804688, },
				[37] = { actorLevel = 253.94700622559, },
				[38] = { actorLevel = 265.17199707031, },
				[39] = { actorLevel = 276.62298583984, },
				[40] = { actorLevel = 288.29998779297, },
			},
		},
	}
}
skills["LivingLightningZap"] = {
	name = "Zap",
	hidden = true,
	description = "Teleport to a target, dealing Lightning Attack Damage.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Lightning] = true, [SkillType.Chains] = true, [SkillType.Melee] = true, [SkillType.CannotTerrainChain] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { critChance = 9, storedUses = 1, levelRequirement = 0, cooldown = 0.25, },
	},
	statSets = {
		[1] = {
			label = "Zap",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "skill_stat_descriptions",
			baseFlags = {
				attack = true,
				melee = true,
				chaining = true,
			},
			constantStats = {
				{ "number_of_chains", 3 },
				{ "living_lightning_damage_+%_final_per_additional_hit", -30 },
			},
			stats = {
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}
skills["DeathFromAboveDaemonMinion"] = {
	name = "Death From Above",
	hidden = true,
	description = "Fires a flare at a target location, attaching to an enemy if it lands on one. Then fires a series of arrow volleys centred around the flare.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.Rain] = true, [SkillType.Area] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesNumberModifiersNotApplied] = true, },
	castTime = 1,
	qualityStats = {
	},
	levels = {
		[1] = { baseMultiplier = 11.4, storedUses = 1, levelRequirement = 0, cooldown = 40, },
	},
	statSets = {
		[1] = {
			label = "Death From Above",
			incrementalEffectiveness = 0.054999999701977,
			statDescriptionScope = "death_from_above",
			statMap = {
				["death_from_above_number_of_volleys"] = {
					skill("dpsMultiplier", nil),
				},
			},
			baseFlags = {
				attack = true,
				projectile = true,
				area = true,
			},
			constantStats = {
				{ "death_from_above_volley_delay_ms", 2000 },
				{ "death_from_above_number_of_volleys", 4 },
				{ "explosion_delay_ms", 250 },
				{ "active_skill_base_area_of_effect_radius", 140 },
				{ "active_skill_base_secondary_area_of_effect_radius", 75 },
				{ "command_minion_marker_additional_time_ms", 300 },
			},
			stats = {
				"is_commandable_skill",
				"base_is_projectile",
				"is_area_damage",
				"skill_cannot_be_frozen",
				"skill_cannot_be_electrocuted",
				"skill_cannot_be_knocked_back",
				"skill_cannot_be_stunned",
				"modifiers_to_projectile_count_do_not_apply",
			},
			levels = {
				[1] = { actorLevel = 1, },
			},
		},
	}
}