-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["Hayoxi's Soul Core of Heatproofing"] = {
		["helmet"] = {
				type = "Rune",
				"+30% of Armour also applies to Cold Damage",
				statOrder = { 4481 },
		},
	},
	["Zalatl's Soul Core of Insulation"] = {
		["boots"] = {
				type = "Rune",
				"+30% of Armour also applies to Lightning Damage",
				statOrder = { 4483 },
		},
	},
	["Topotante's Soul Core of Dampening"] = {
		["gloves"] = {
				type = "Rune",
				"+30% of Armour also applies to Fire Damage",
				statOrder = { 4482 },
		},
	},
	["Atmohua's Soul Core of Retreat"] = {
		["body armour"] = {
				type = "Rune",
				"30% faster start of Energy Shield Recharge",
				statOrder = { 963 },
		},
	},
	["Quipolatl's Soul Core of Flow"] = {
		["helmet"] = {
				type = "Rune",
				"8% increased Skill Effect Duration",
				"8% increased Cooldown Recovery Rate",
				statOrder = { 1569, 4507 },
		},
	},
	["Tzamoto's Soul Core of Ferocity"] = {
		["helmet"] = {
				type = "Rune",
				"+4 to Maximum Rage",
				statOrder = { 8886 },
		},
	},
	["Uromoti's Soul Core of Attenuation"] = {
		["boots"] = {
				type = "Rune",
				"15% increased Curse Duration",
				"15% increased Poison Duration",
				statOrder = { 1463, 2775 },
		},
	},
	["Opiloti's Soul Core of Assault"] = {
		["weapon"] = {
				type = "Rune",
				"50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge",
				statOrder = { 5097 },
		},
		["caster"] = {
				type = "Rune",
				"50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge",
				statOrder = { 5097 },
		},
	},
	["Guatelitzi's Soul Core of Endurance"] = {
		["weapon"] = {
				type = "Rune",
				"50% chance when you gain an Endurance Charge to gain an additional Endurance Charge",
				statOrder = { 5096 },
		},
		["caster"] = {
				type = "Rune",
				"50% chance when you gain an Endurance Charge to gain an additional Endurance Charge",
				statOrder = { 5096 },
		},
	},
	["Xopec's Soul Core of Power"] = {
		["weapon"] = {
				type = "Rune",
				"50% chance when you gain a Power Charge to gain an additional Power Charge",
				statOrder = { 5098 },
		},
		["caster"] = {
				type = "Rune",
				"50% chance when you gain a Power Charge to gain an additional Power Charge",
				statOrder = { 5098 },
		},
	},
	["Estazunti's Soul Core of Convalescence"] = {
		["boots"] = {
				type = "Rune",
				"10% increased speed of Recoup Effects",
				statOrder = { 8937 },
		},
	},
	["Tacati's Soul Core of Affliction"] = {
		["helmet"] = {
				type = "Rune",
				"Enemies you Curse have -4% to Chaos Resistance",
				statOrder = { 3606 },
		},
	},
	["Cholotl's Soul Core of War"] = {
		["bow"] = {
				type = "Rune",
				"20% increased Projectile Speed",
				statOrder = { 872 },
		},
	},
	["Citaqualotl's Soul Core of Foulness"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 19 to 29 Chaos damage",
				statOrder = { 1223 },
		},
	},
	["Xipocado's Soul Core of Dominion"] = {
		["caster"] = {
				type = "Rune",
				"Minions deal 40% increased Damage with Command Skills",
				statOrder = { 8347 },
		},
		["sceptre"] = {
				type = "Rune",
				"Minions deal 40% increased Damage with Command Skills",
				statOrder = { 8347 },
		},
	},
	["Soul Core of Tacati"] = {
		["weapon"] = {
				type = "Rune",
				"15% chance to Poison on Hit with this weapon",
				statOrder = { 7224 },
		},
		["armour"] = {
				type = "Rune",
				"+11% to Chaos Resistance",
				statOrder = { 957 },
		},
	},
	["Soul Core of Opiloti"] = {
		["weapon"] = {
				type = "Rune",
				"15% chance to cause Bleeding on Hit",
				statOrder = { 2147 },
		},
		["helmet"] = {
				type = "Rune",
				"20% increased Charm Charges gained",
				statOrder = { 5177 },
		},
	},
	["Soul Core of Jiquani"] = {
		["weapon"] = {
				type = "Rune",
				"Recover 2% of maximum Life on Kill",
				statOrder = { 1434 },
		},
		["body armour"] = {
				type = "Rune",
				"3% increased maximum Life",
				statOrder = { 867 },
		},
	},
	["Soul Core of Zalatl"] = {
		["weapon"] = {
				type = "Rune",
				"Recover 2% of maximum Mana on Kill",
				statOrder = { 1436 },
		},
		["helmet"] = {
				type = "Rune",
				"3% increased maximum Mana",
				statOrder = { 869 },
		},
	},
	["Soul Core of Citaqualotl"] = {
		["weapon"] = {
				type = "Rune",
				"30% increased Elemental Damage with Attacks",
				statOrder = { 856 },
		},
		["armour"] = {
				type = "Rune",
				"+5% to all Elemental Resistances",
				statOrder = { 953 },
		},
	},
	["Soul Core of Puhuarte"] = {
		["weapon"] = {
				type = "Rune",
				"30% increased Flammability Magnitude",
				statOrder = { 984 },
		},
		["gloves"] = {
				type = "Rune",
				"+1% to Maximum Fire Resistance",
				statOrder = { 949 },
		},
	},
	["Soul Core of Tzamoto"] = {
		["weapon"] = {
				type = "Rune",
				"30% increased Freeze Buildup",
				statOrder = { 986 },
		},
		["helmet"] = {
				type = "Rune",
				"+1% to Maximum Cold Resistance",
				statOrder = { 950 },
		},
	},
	["Soul Core of Xopec"] = {
		["weapon"] = {
				type = "Rune",
				"30% increased chance to Shock",
				statOrder = { 988 },
		},
		["boots"] = {
				type = "Rune",
				"+1% to Maximum Lightning Resistance",
				statOrder = { 951 },
		},
	},
	["Soul Core of Azcapa"] = {
		["weapon"] = {
				type = "Rune",
				"+15 to Spirit",
				statOrder = { 871 },
		},
		["gloves"] = {
				type = "Rune",
				"10% increased Quantity of Gold Dropped by Slain Enemies",
				statOrder = { 6384 },
		},
	},
	["Soul Core of Topotante"] = {
		["weapon"] = {
				type = "Rune",
				"Attacks with this Weapon Penetrate 15% Elemental Resistances",
				statOrder = { 3319 },
		},
		["boots"] = {
				type = "Rune",
				"25% increased Elemental Ailment Threshold",
				statOrder = { 4130 },
		},
	},
	["Soul Core of Quipolatl"] = {
		["weapon"] = {
				type = "Rune",
				"5% increased Attack Speed",
				statOrder = { 916 },
		},
		["boots"] = {
				type = "Rune",
				"15% reduced Slowing Potency of Debuffs on You",
				statOrder = { 4572 },
		},
	},
	["Soul Core of Ticaba"] = {
		["weapon"] = {
				type = "Rune",
				"+5% to Critical Damage Bonus",
				statOrder = { 915 },
		},
		["body armour"] = {
				type = "Rune",
				"Hits against you have 20% reduced Critical Damage Bonus",
				statOrder = { 946 },
		},
	},
	["Soul Core of Atmohua"] = {
		["weapon"] = {
				type = "Rune",
				"Convert 20% of Requirements to Strength",
				statOrder = { 7228 },
		},
		["armour"] = {
				type = "Rune",
				"Convert 20% of Requirements to Strength",
				statOrder = { 7228 },
		},
	},
	["Soul Core of Cholotl"] = {
		["weapon"] = {
				type = "Rune",
				"Convert 20% of Requirements to Dexterity",
				statOrder = { 7226 },
		},
		["armour"] = {
				type = "Rune",
				"Convert 20% of Requirements to Dexterity",
				statOrder = { 7226 },
		},
	},
	["Soul Core of Zantipi"] = {
		["weapon"] = {
				type = "Rune",
				"Convert 20% of Requirements to Intelligence",
				statOrder = { 7227 },
		},
		["armour"] = {
				type = "Rune",
				"Convert 20% of Requirements to Intelligence",
				statOrder = { 7227 },
		},
	},
	["Desert Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 7 to 11 Fire Damage",
				statOrder = { 821 },
		},
		["armour"] = {
				type = "Rune",
				"+12% to Fire Resistance",
				statOrder = { 954 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 8% of Damage as Extra Fire Damage",
				statOrder = { 844 },
		},
	},
	["Glacial Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 6 to 10 Cold Damage",
				statOrder = { 822 },
		},
		["armour"] = {
				type = "Rune",
				"+12% to Cold Resistance",
				statOrder = { 955 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 8% of Damage as Extra Cold Damage",
				statOrder = { 846 },
		},
	},
	["Storm Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 1 to 20 Lightning Damage",
				statOrder = { 823 },
		},
		["armour"] = {
				type = "Rune",
				"+12% to Lightning Resistance",
				statOrder = { 956 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 8% of Damage as Extra Lightning Damage",
				statOrder = { 848 },
		},
	},
	["Iron Rune"] = {
		["weapon"] = {
				type = "Rune",
				"16% increased Physical Damage",
				statOrder = { 819 },
		},
		["armour"] = {
				type = "Rune",
				"16% increased Armour, Evasion and Energy Shield",
				statOrder = { 1361 },
		},
		["caster"] = {
				type = "Rune",
				"25% increased Spell Damage",
				statOrder = { 850 },
		},
	},
	["Body Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Leeches 2.5% of Physical Damage as Life",
				statOrder = { 968 },
		},
		["armour"] = {
				type = "Rune",
				"+30 to maximum Life",
				statOrder = { 866 },
		},
		["caster"] = {
				type = "Rune",
				"+30 to maximum Energy Shield",
				statOrder = { 864 },
		},
	},
	["Mind Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Leeches 2% of Physical Damage as Mana",
				statOrder = { 974 },
		},
		["armour"] = {
				type = "Rune",
				"+25 to maximum Mana",
				statOrder = { 868 },
		},
		["caster"] = {
				type = "Rune",
				"+40 to maximum Mana",
				statOrder = { 868 },
		},
	},
	["Rebirth Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 20 Life per Enemy Killed",
				statOrder = { 971 },
		},
		["armour"] = {
				type = "Rune",
				"Regenerate 0.3% of maximum Life per second",
				statOrder = { 1614 },
		},
		["caster"] = {
				type = "Rune",
				"15% increased Energy Shield Recharge Rate",
				statOrder = { 962 },
		},
	},
	["Inspiration Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 16 Mana per Enemy Killed",
				statOrder = { 976 },
		},
		["armour"] = {
				type = "Rune",
				"15% increased Mana Regeneration Rate",
				statOrder = { 972 },
		},
		["caster"] = {
				type = "Rune",
				"20% increased Mana Regeneration Rate",
				statOrder = { 972 },
		},
	},
	["Stone Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Causes 25% increased Stun Buildup",
				statOrder = { 981 },
		},
		["armour"] = {
				type = "Rune",
				"+60 to Stun Threshold",
				statOrder = { 990 },
		},
		["caster"] = {
				type = "Rune",
				"Gain additional Stun Threshold equal to 12% of maximum Energy Shield",
				statOrder = { 9364 },
		},
	},
	["Vision Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+80 to Accuracy Rating",
				statOrder = { 824 },
		},
		["armour"] = {
				type = "Rune",
				"10% increased Life and Mana Recovery from Flasks",
				statOrder = { 6145 },
		},
		["caster"] = {
				type = "Rune",
				"20% increased Critical Hit Chance for Spells",
				statOrder = { 931 },
		},
	},
	["Lesser Desert Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 4 to 6 Fire Damage",
				statOrder = { 821 },
		},
		["armour"] = {
				type = "Rune",
				"+10% to Fire Resistance",
				statOrder = { 954 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 6% of Damage as Extra Fire Damage",
				statOrder = { 844 },
		},
	},
	["Lesser Glacial Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 3 to 5 Cold Damage",
				statOrder = { 822 },
		},
		["armour"] = {
				type = "Rune",
				"+10% to Cold Resistance",
				statOrder = { 955 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 6% of Damage as Extra Cold Damage",
				statOrder = { 846 },
		},
	},
	["Lesser Storm Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 1 to 10 Lightning Damage",
				statOrder = { 823 },
		},
		["armour"] = {
				type = "Rune",
				"+10% to Lightning Resistance",
				statOrder = { 956 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 6% of Damage as Extra Lightning Damage",
				statOrder = { 848 },
		},
	},
	["Lesser Iron Rune"] = {
		["weapon"] = {
				type = "Rune",
				"14% increased Physical Damage",
				statOrder = { 819 },
		},
		["armour"] = {
				type = "Rune",
				"14% increased Armour, Evasion and Energy Shield",
				statOrder = { 1361 },
		},
		["caster"] = {
				type = "Rune",
				"20% increased Spell Damage",
				statOrder = { 850 },
		},
	},
	["Lesser Body Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Leeches 2% of Physical Damage as Life",
				statOrder = { 968 },
		},
		["armour"] = {
				type = "Rune",
				"+20 to maximum Life",
				statOrder = { 866 },
		},
		["caster"] = {
				type = "Rune",
				"+25 to maximum Energy Shield",
				statOrder = { 864 },
		},
	},
	["Lesser Mind Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Leeches 1.5% of Physical Damage as Mana",
				statOrder = { 974 },
		},
		["armour"] = {
				type = "Rune",
				"+15 to maximum Mana",
				statOrder = { 868 },
		},
		["caster"] = {
				type = "Rune",
				"+30 to maximum Mana",
				statOrder = { 868 },
		},
	},
	["Lesser Rebirth Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 10 Life per Enemy Killed",
				statOrder = { 971 },
		},
		["armour"] = {
				type = "Rune",
				"Regenerate 0.25% of maximum Life per second",
				statOrder = { 1614 },
		},
		["caster"] = {
				type = "Rune",
				"12% increased Energy Shield Recharge Rate",
				statOrder = { 962 },
		},
	},
	["Lesser Inspiration Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 8 Mana per Enemy Killed",
				statOrder = { 976 },
		},
		["armour"] = {
				type = "Rune",
				"12% increased Mana Regeneration Rate",
				statOrder = { 972 },
		},
		["caster"] = {
				type = "Rune",
				"16% increased Mana Regeneration Rate",
				statOrder = { 972 },
		},
	},
	["Lesser Stone Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Causes 20% increased Stun Buildup",
				statOrder = { 981 },
		},
		["armour"] = {
				type = "Rune",
				"+40 to Stun Threshold",
				statOrder = { 990 },
		},
		["caster"] = {
				type = "Rune",
				"Gain additional Stun Threshold equal to 10% of maximum Energy Shield",
				statOrder = { 9364 },
		},
	},
	["Lesser Vision Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+50 to Accuracy Rating",
				statOrder = { 824 },
		},
		["armour"] = {
				type = "Rune",
				"8% increased Life and Mana Recovery from Flasks",
				statOrder = { 6145 },
		},
		["caster"] = {
				type = "Rune",
				"16% increased Critical Hit Chance for Spells",
				statOrder = { 931 },
		},
	},
	["Greater Desert Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 13 to 16 Fire Damage",
				statOrder = { 821 },
		},
		["armour"] = {
				type = "Rune",
				"+14% to Fire Resistance",
				statOrder = { 954 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 10% of Damage as Extra Fire Damage",
				statOrder = { 844 },
		},
	},
	["Greater Glacial Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 9 to 15 Cold Damage",
				statOrder = { 822 },
		},
		["armour"] = {
				type = "Rune",
				"+14% to Cold Resistance",
				statOrder = { 955 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 10% of Damage as Extra Cold Damage",
				statOrder = { 846 },
		},
	},
	["Greater Storm Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 1 to 30 Lightning Damage",
				statOrder = { 823 },
		},
		["armour"] = {
				type = "Rune",
				"+14% to Lightning Resistance",
				statOrder = { 956 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 10% of Damage as Extra Lightning Damage",
				statOrder = { 848 },
		},
	},
	["Greater Iron Rune"] = {
		["weapon"] = {
				type = "Rune",
				"18% increased Physical Damage",
				statOrder = { 819 },
		},
		["armour"] = {
				type = "Rune",
				"18% increased Armour, Evasion and Energy Shield",
				statOrder = { 1361 },
		},
		["caster"] = {
				type = "Rune",
				"30% increased Spell Damage",
				statOrder = { 850 },
		},
	},
	["Greater Body Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Leeches 3% of Physical Damage as Life",
				statOrder = { 968 },
		},
		["armour"] = {
				type = "Rune",
				"+40 to maximum Life",
				statOrder = { 866 },
		},
		["caster"] = {
				type = "Rune",
				"+35 to maximum Energy Shield",
				statOrder = { 864 },
		},
	},
	["Greater Mind Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Leeches 2.5% of Physical Damage as Mana",
				statOrder = { 974 },
		},
		["armour"] = {
				type = "Rune",
				"+35 to maximum Mana",
				statOrder = { 868 },
		},
		["caster"] = {
				type = "Rune",
				"+50 to maximum Mana",
				statOrder = { 868 },
		},
	},
	["Greater Rebirth Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 30 Life per Enemy Killed",
				statOrder = { 971 },
		},
		["armour"] = {
				type = "Rune",
				"Regenerate 0.35% of maximum Life per second",
				statOrder = { 1614 },
		},
		["caster"] = {
				type = "Rune",
				"18% increased Energy Shield Recharge Rate",
				statOrder = { 962 },
		},
	},
	["Greater Inspiration Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 24 Mana per Enemy Killed",
				statOrder = { 976 },
		},
		["armour"] = {
				type = "Rune",
				"18% increased Mana Regeneration Rate",
				statOrder = { 972 },
		},
		["caster"] = {
				type = "Rune",
				"24% increased Mana Regeneration Rate",
				statOrder = { 972 },
		},
	},
	["Greater Stone Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Causes 30% increased Stun Buildup",
				statOrder = { 981 },
		},
		["armour"] = {
				type = "Rune",
				"+80 to Stun Threshold",
				statOrder = { 990 },
		},
		["caster"] = {
				type = "Rune",
				"Gain additional Stun Threshold equal to 14% of maximum Energy Shield",
				statOrder = { 9364 },
		},
	},
	["Greater Vision Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+110 to Accuracy Rating",
				statOrder = { 824 },
		},
		["armour"] = {
				type = "Rune",
				"12% increased Life and Mana Recovery from Flasks",
				statOrder = { 6145 },
		},
		["caster"] = {
				type = "Rune",
				"24% increased Critical Hit Chance for Spells",
				statOrder = { 931 },
		},
	},
	["Lesser Robust Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+6 to Strength",
				statOrder = { 943 },
		},
		["armour"] = {
				type = "Rune",
				"+6 to Strength",
				statOrder = { 943 },
		},
		["caster"] = {
				type = "Rune",
				"+6 to Strength",
				statOrder = { 943 },
		},
	},
	["Robust Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+8 to Strength",
				statOrder = { 943 },
		},
		["armour"] = {
				type = "Rune",
				"+8 to Strength",
				statOrder = { 943 },
		},
		["caster"] = {
				type = "Rune",
				"+8 to Strength",
				statOrder = { 943 },
		},
	},
	["Greater Robust Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+10 to Strength",
				statOrder = { 943 },
		},
		["armour"] = {
				type = "Rune",
				"+10 to Strength",
				statOrder = { 943 },
		},
		["caster"] = {
				type = "Rune",
				"+10 to Strength",
				statOrder = { 943 },
		},
	},
	["Lesser Adept Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+6 to Dexterity",
				statOrder = { 944 },
		},
		["armour"] = {
				type = "Rune",
				"+6 to Dexterity",
				statOrder = { 944 },
		},
		["caster"] = {
				type = "Rune",
				"+6 to Dexterity",
				statOrder = { 944 },
		},
	},
	["Adept Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+8 to Dexterity",
				statOrder = { 944 },
		},
		["armour"] = {
				type = "Rune",
				"+8 to Dexterity",
				statOrder = { 944 },
		},
		["caster"] = {
				type = "Rune",
				"+8 to Dexterity",
				statOrder = { 944 },
		},
	},
	["Greater Adept Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+10 to Dexterity",
				statOrder = { 944 },
		},
		["armour"] = {
				type = "Rune",
				"+10 to Dexterity",
				statOrder = { 944 },
		},
		["caster"] = {
				type = "Rune",
				"+10 to Dexterity",
				statOrder = { 944 },
		},
	},
	["Lesser Resolve Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+6 to Intelligence",
				statOrder = { 945 },
		},
		["armour"] = {
				type = "Rune",
				"+6 to Intelligence",
				statOrder = { 945 },
		},
		["caster"] = {
				type = "Rune",
				"+6 to Intelligence",
				statOrder = { 945 },
		},
	},
	["Resolve Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+8 to Intelligence",
				statOrder = { 945 },
		},
		["armour"] = {
				type = "Rune",
				"+8 to Intelligence",
				statOrder = { 945 },
		},
		["caster"] = {
				type = "Rune",
				"+8 to Intelligence",
				statOrder = { 945 },
		},
	},
	["Greater Resolve Rune"] = {
		["weapon"] = {
				type = "Rune",
				"+10 to Intelligence",
				statOrder = { 945 },
		},
		["armour"] = {
				type = "Rune",
				"+10 to Intelligence",
				statOrder = { 945 },
		},
		["caster"] = {
				type = "Rune",
				"+10 to Intelligence",
				statOrder = { 945 },
		},
	},
	["Lesser Tempered Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 3 to 4 Physical Damage",
				statOrder = { 820 },
		},
		["armour"] = {
				type = "Rune",
				"6 to 9 Physical Thorns damage",
				statOrder = { 9483 },
		},
	},
	["Tempered Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 6 to 9 Physical Damage",
				statOrder = { 820 },
		},
		["armour"] = {
				type = "Rune",
				"14 to 21 Physical Thorns damage",
				statOrder = { 9483 },
		},
	},
	["Greater Tempered Rune"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 9 to 12 Physical Damage",
				statOrder = { 820 },
		},
		["armour"] = {
				type = "Rune",
				"31 to 52 Physical Thorns damage",
				statOrder = { 9483 },
		},
	},
	["Greater Rune of Leadership"] = {
		["weapon"] = {
				type = "Rune",
				"Minions gain 10% of their Physical Damage as Extra Lightning Damage",
				statOrder = { 8391 },
		},
		["armour"] = {
				type = "Rune",
				"Minions take 10% of Physical Damage as Lightning Damage",
				statOrder = { 8392 },
		},
	},
	["Greater Rune of Tithing"] = {
		["weapon"] = {
				type = "Rune",
				"Meta Skills gain 10% increased Energy",
				statOrder = { 5919 },
		},
		["armour"] = {
				type = "Rune",
				"1 to 100 Lightning Thorns damage",
				statOrder = { 9482 },
		},
	},
	["Greater Rune of Alacrity"] = {
		["weapon"] = {
				type = "Rune",
				"8% increased Skill Speed",
				statOrder = { 826 },
		},
		["armour"] = {
				type = "Rune",
				"Debuffs on you expire 8% faster",
				statOrder = { 5638 },
		},
	},
	["Greater Rune of Nobility"] = {
		["weapon"] = {
				type = "Rune",
				"Attacks with this Weapon have 10% chance to inflict Lightning Exposure",
				statOrder = { 7159 },
		},
		["armour"] = {
				type = "Rune",
				"10% reduced effect of Shock on you",
				statOrder = { 9107 },
		},
	},
	["Hedgewitch Assandra's Rune of Wisdom"] = {
		["caster"] = {
				type = "Rune",
				"+1 to Level of all Spell Skills",
				statOrder = { 919 },
		},
	},
	["Saqawal's Rune of the Sky"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 5% of Damage as Extra Damage of all Elements",
				statOrder = { 8552 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 5% of Damage as Extra Damage of all Elements",
				statOrder = { 8552 },
		},
	},
	["Fenumus' Rune of Agony"] = {
		["weapon"] = {
				type = "Rune",
				"Gain 13% of Damage as Extra Chaos Damage",
				statOrder = { 1599 },
		},
		["caster"] = {
				type = "Rune",
				"Gain 13% of Damage as Extra Chaos Damage",
				statOrder = { 1599 },
		},
	},
	["Farrul's Rune of Grace"] = {
		["boots"] = {
				type = "Rune",
				"6% reduced Movement Speed Penalty from using Skills while moving",
				statOrder = { 8467 },
		},
	},
	["Farrul's Rune of the Chase"] = {
		["boots"] = {
				type = "Rune",
				"5% increased Movement Speed",
				statOrder = { 825 },
		},
	},
	["Craiceann's Rune of Warding"] = {
		["body armour"] = {
				type = "Rune",
				"40% reduced effect of Curses on you",
				statOrder = { 1832 },
		},
	},
	["Saqawal's Rune of Memory"] = {
		["helmet"] = {
				type = "Rune",
				"2% increased Experience gain",
				statOrder = { 1394 },
		},
	},
	["Saqawal's Rune of Erosion"] = {
		["helmet"] = {
				type = "Rune",
				"20% increased Exposure Effect",
				statOrder = { 6032 },
		},
	},
	["Farrul's Rune of the Hunt"] = {
		["weapon"] = {
				type = "Rune",
				"50% increased Attack Damage against Rare or Unique Enemies",
				statOrder = { 4352 },
		},
	},
	["Craiceann's Rune of Recovery"] = {
		["body armour"] = {
				type = "Rune",
				"50% increased Energy Shield Recharge Rate",
				statOrder = { 962 },
		},
	},
	["Courtesan Mannan's Rune of Cruelty"] = {
		["gloves"] = {
				type = "Rune",
				"15% increased Magnitude of Damaging Ailments you inflict",
				statOrder = { 5605 },
		},
	},
	["Thane Grannell's Rune of Mastery"] = {
		["gloves"] = {
				type = "Rune",
				"20% increased Magnitude of Non-Damaging Ailments you inflict",
				statOrder = { 8532 },
		},
	},
	["Fenumus' Rune of Spinning"] = {
		["gloves"] = {
				type = "Rune",
				"8% increased Cast Speed",
				statOrder = { 938 },
		},
	},
	["Countess Seske's Rune of Archery"] = {
		["bow"] = {
				type = "Rune",
				"Bow Attacks fire an additional Arrow",
				statOrder = { 941 },
		},
	},
	["Thane Girt's Rune of Wildness"] = {
		["caster"] = {
				type = "Rune",
				"25% chance for Spell Skills to fire 2 additional Projectiles",
				statOrder = { 9267 },
		},
	},
	["Fenumus' Rune of Draining"] = {
		["gloves"] = {
				type = "Rune",
				"20% increased Withered Magnitude",
				statOrder = { 9734 },
		},
	},
	["Thane Myrk's Rune of Summer"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 23 to 34 Fire Damage",
				statOrder = { 821 },
		},
	},
	["Lady Hestra's Rune of Winter"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 19 to 28 Cold Damage",
				statOrder = { 822 },
		},
	},
	["Thane Leld's Rune of Spring"] = {
		["weapon"] = {
				type = "Rune",
				"Adds 1 to 60 Lightning Damage",
				statOrder = { 823 },
		},
	},
	["The Greatwolf's Rune of Claws"] = {
		["gloves"] = {
				type = "Rune",
				"Adds 5 to 12 Physical Damage to Attacks",
				statOrder = { 840 },
		},
	},
	["The Greatwolf's Rune of Willpower"] = {
		["body armour"] = {
				type = "Rune",
				"10% of Damage is taken from Mana before Life",
				statOrder = { 2352 },
		},
	},
	["Talisman of Sirrius"] = {
		["gloves"] = {
				type = "Rune",
				"8% increased Attack Speed",
				statOrder = { 937 },
		},
	},
	["Talisman of Thruldana"] = {
		["weapon"] = {
				type = "Rune",
				"25% reduced Poison Duration",
				"Targets can be affected by +1 of your Poisons at the same time",
				statOrder = { 2775, 8612 },
		},
	},
	["Talisman of Grold"] = {
		["gloves"] = {
				type = "Rune",
				"15% increased total Power counted by Warcries",
				statOrder = { 9708 },
		},
	},
	["Talisman of Eeshta"] = {
		["helmet"] = {
				type = "Rune",
				"10% increased Cost Efficiency",
				statOrder = { 4568 },
		},
	},
	["Talisman of Egrin"] = {
		["helmet"] = {
				type = "Rune",
				"Enemies you Curse take 5% increased Damage",
				statOrder = { 3316 },
		},
	},
	["Talisman of Maxarius"] = {
		["body armour"] = {
				type = "Rune",
				"+1 Charm Slot",
				statOrder = { 8602 },
		},
	},
	["Talisman of Ralakesh"] = {
		["helmet"] = {
				type = "Rune",
				"6% increased Reservation Efficiency of Minion Skills",
				statOrder = { 8397 },
		},
	},
	["Serpent Talisman"] = {
		["gloves"] = {
				type = "Rune",
				"5% increased Curse Magnitudes",
				statOrder = { 2256 },
		},
	},
	["Primate Talisman"] = {
		["helmet"] = {
				type = "Rune",
				"Minions have 12% increased maximum Life",
				statOrder = { 958 },
		},
	},
	["Owl Talisman"] = {
		["focus"] = {
				type = "Rune",
				"10% increased Cooldown Recovery Rate",
				statOrder = { 4507 },
		},
	},
	["Cat Talisman"] = {
		["gloves"] = {
				type = "Rune",
				"15% increased Accuracy Rating",
				statOrder = { 1264 },
		},
	},
	["Wolf Talisman"] = {
		["gloves"] = {
				type = "Rune",
				"10% increased Magnitude of Bleeding you inflict",
				statOrder = { 4626 },
		},
	},
	["Stag Talisman"] = {
		["helmet"] = {
				type = "Rune",
				"50% increased Thorns Critical Hit Chance",
				statOrder = { 9472 },
		},
	},
	["Boar Talisman"] = {
		["gloves"] = {
				type = "Rune",
				"Gain 1 Rage on Melee Hit",
				statOrder = { 6339 },
		},
	},
	["Bear Talisman"] = {
		["helmet"] = {
				type = "Rune",
				"8% increased Area of Effect",
				statOrder = { 1554 },
		},
	},
	["Ox Talisman"] = {
		["shield"] = {
				type = "Rune",
				"10% increased Block chance",
				statOrder = { 828 },
		},
	},
	["Rabbit Talisman"] = {
		["body armour"] = {
				type = "Rune",
				"8% increased Rarity of Items found",
				statOrder = { 913 },
		},
	},
	["Fox Talisman"] = {
		["body armour"] = {
				type = "Rune",
				"+2% to Quality of all Skills",
				statOrder = { 4150 },
		},
	},
}